// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Lock$Type } from "./Lock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Lock"]: Lock$Type;
    ["contracts/Lock.sol:Lock"]: Lock$Type;
  }

  interface ContractTypesMap {
    ["Lock"]: GetContractReturnType<Lock$Type["abi"]>;
    ["contracts/Lock.sol:Lock"]: GetContractReturnType<Lock$Type["abi"]>;
  }
}
