// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Storage$Type } from "./Storage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Storage"]: Storage$Type;
    ["contracts/Storage.sol:Storage"]: Storage$Type;
  }

  interface ContractTypesMap {
    ["Storage"]: GetContractReturnType<Storage$Type["abi"]>;
    ["contracts/Storage.sol:Storage"]: GetContractReturnType<Storage$Type["abi"]>;
  }
}
